"""add avatar to user

Revision ID: 20260511_001
Revises: 
Create Date: 2026-05-11 06:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260511_001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Check if table exists before adding column
    # In a real autogenerated migration, this would be more specific
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column('users', 'avatar')
